version: '3'
services:
  api:
    image: hackerbay-backend
    build: .
    networks:
      - backend
    ports:
      - "4000:4000"

  web-cli:
    image: hackerbay-backend
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge